@TodosApi_HostAddress = http://localhost:1337


GET {{TodosApi_HostAddress}}/status
Accept: application/json

###
POST {{TodosApi_HostAddress}}/todos
Accept: application/json
Content-Type: application/json
 
{
    "description": "Eat lunch"
}

###
GET {{TodosApi_HostAddress}}/todos
Accept: application/json